### ISSUE TITLE
缺少数据集的预处理

### ISSUE THREAD

**Issue by Li-fAngyU** [HKUDS/MAERec#1]
你好，直接通过`python main.py --data books`是无法run的。应该是缺少对数据集的处理步骤。

**Comment by helloelwin** [comment]
谢谢反馈！检查发现应该是 books 的 trn 上传错误了，其他两个数据集应该是可以运行的，已经重新上传了文件。

**Comment by Li-fAngyU** [comment]
@HelloElwin 谢谢解答，请问linux下该如何解压datasets/里的文件呢？

还有请问方便提供数据集预处理的源代码吗？

**Comment by helloelwin** [comment]
> @HelloElwin 谢谢解答，请问linux下该如何解压datasets/里的文件呢？

解压方法应该可以在网上搜索到。

> 还有请问方便提供数据集预处理的源代码吗？

好的，我们后续会整理数据预处理方法并上传。

谢谢！
