### ISSUE TITLE
测试集负样本问题

### ISSUE THREAD

**Issue by wcnm231** [HKUDS/MAERec#10]
你好，请问我在github上看到那你对数据集的说明，neg是测试序列的负样本，请问这个作用是什么，以及文中说的是对比学习方法有弊端，但是为什么model代码还涉及到正负样本对的获取

**Comment by helloelwin** [comment]
谢谢评论！neg 是用于评估模型能否选择正确商品进行推荐的负样本，本身不用于训练。模型在推荐任务训练时获取负样本以计算对应的损失函数（详见原文），以及获取负样本用于自监督学习。文中并不是指不应该使用正负样本，而是提出了一种生成式的可能比传统对比学习更好的自监督方式。

**Comment by wcnm231** [comment]
谢谢回复，请问可以详细说一下论文整个流程吗，比如从输入用户历史交互序列到最终的输出结果，这里我没有弄太明白，transformer序列编码器是对经过前面解码器重建边的输出进行处理吗，最终的推荐结果是从哪里得出的呢

**Comment by helloelwin** [comment]
你好，谢谢你的关注！完整流程还请参考原文，由于时间有限不能在这里完整解释，非常抱歉。
