### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by wcnm231** [HKUDS/MAERec#11]
请问在您的construct.py文件中，生成的trn文件里面的数据形式是(1,2) 1表示项目1,2之间有边，那么在文件handler中类DataHander的load_data函数下， trn_data = SeqRecTrnDataset(seq)这种输出数据的形式和trn文件不一致，这两者没什么联系吗，其次可以解释下SeqRecTrnDataset和SeqRecTstDataset这两个类的作用吗，为什么把数据集处理成返回的（input_ids,target_pos,target_neg）这种形式

**Comment by helloelwin** [comment]
谢谢您的问题！handler 中的类是加载数据集用于训练，所以转换了格式以方便训练，具体可以参考 handler 代码以及训练代码中的实现以及使用方法。

**Comment by wcnm231** [comment]
好的，谢谢你的回复，所以最终训练模型的·数据集不是seq文件数据的形式，而是进一步处理成（input_ids,target_pos,target_neg）这种形式用于训练对吧
