### ISSUE TITLE
Questions about algorithmic thinking

### ISSUE THREAD

**Issue by Keplerrrrrrrr** [HKUDS/MAERec#5]
Hello, thanks for your outstanding work! 
I am interested in your paper "Adaptive Path Masking", the idea of expanding and sampling the nodes in the graph. 
Is it a kind of Heuristically Search?

**Comment by helloelwin** [comment]
Hi, thanks for the question! I think there's a difference between them. Expanding and sampling are used to generate the transition paths from anchor nodes. The process stops after a few steps (as specified in the hyper-parameters) and it is not 'searching' for something. Instead, it simply produces randomly generated transition paths from anchor nodes.
