### ISSUE TITLE
Question about the local graph

### ISSUE THREAD

**Issue by MTandHJ** [HKUDS/MAERec#7]
Hi,

It's not easy for me to connect the implementation of local graph to the sampling of candidates. 
It would be helpful if you could provide some detailed references.

Thanks !

**Comment by helloelwin** [comment]
Thanks for your interest! The "local graph" just refer to the local neighbors of a node. The local graph class in our code is used to sample the candidate anchor nodes for masking according their score calculated in the forward function. These candidates are then further used to sample the masked sequences. Hope this can help you a bit, and you can further refer to our paper for more detailed explanation about this transition path masking process : )
