### ISSUE TITLE
datasets 中 neg 的采样方法

### ISSUE THREAD

**Issue by llhhcc** [HKUDS/MAERec#8]
您好，文中的数据集中neg的99个负样本中包含大量的1，请问这样的负样本采样方法是有什么依据吗，这样做是否会影响实验的公平性

**Comment by helloelwin** [comment]
您好，谢谢您的指出。我们的采样方式是在所有负样本中随机抽取，但发现确实有您说的问题，会去 check 一下是否有 bug。谢谢您的建议！

**Comment by zyx1017** [comment]
> 您好，谢谢您的指出。我们的采样方式是在所有负样本中随机抽取，但发现确实有您说的问题，会去 check 一下是否有 bug。谢谢您的建议！

蹲蹲
