### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by zyx1017** [HKUDS/MAERec#9]
您好！请问一下两个数据集的预处理操作是什么？选取了哪一段时间的数据才能处理成文中提到的密度呢？

**Comment by helloelwin** [comment]
你好，books 使用的是 2014 年的数据，retailrocket 是 2015 年，toys 是 2013-2014。我们保留了所有长度不小于 3 的序列来获得更稀疏的数据。

**Comment by wcnm231** [comment]
但是我打开了数据集中的seq文件发现仍然有交互序列小于3的，这个数据预处理是在给出的代码运行后才会对数据进行处理，还是在运行代码之前已经处理好的

**Comment by helloelwin** [comment]
抱歉这里笔误了，我们是在代码运行前去除了所有长度小于 2 的序列，谢谢指正！
